const APP_ROUTE = {
  ANALYTICAL: 'analytical',
  MODERN: 'modern',
  ECOMMERCE: 'ecommerce',
  CHAT: 'chat',
  NOTES: 'notes',
  MAIL: 'mail',
  CALENDAR: 'calendar',
  CUSTOMERS: 'customers',
  SHOP: 'shop',
  ALERT: 'alert',
  USER_PROFILE: 'user-profile',
  QUILL_EDITOR: 'quill-editor',
  TREEVIEW: 'treeview',
  PRICING: 'pricing',
  TYPOGRAPHY: 'typography',
  FEATHER_ICONS: 'feather-icons',
  TIMELINE: 'timeline',
  FORM_ELEMENTS: 'form-elements',
  FORM_LAYOUT: 'form-layout',
  FORM_CUSTOM: 'form-custom',
  FORM_WIZARD: 'form-wizard',
  TABLES: 'tables',
  WIDGET_FEED: 'widget-feed',
  WIDGET_APPS: 'widget-apps',
  LINE_CHART: 'line-chart',
  GRADIENT_CHART: 'gradient-chart',
  DOUGHNUT_PIE_CHART: 'doughnut-pie-chart',
  AREA_CHART: 'area-chart',
  COLUMN_CHART: 'column-chart',
  CANDLESTICK_CHART: 'candlestick-chart',
  RADIAL_RADAR_CHART: 'radial-radar-chart',
  SIGN_IN: 'sign-in',
  SIGN_UP: 'sign-ip',
  RESET_PASSWORD: 'reset-password',
  ERROR: 'error',
};

export default APP_ROUTE;
