import * as Icon from 'react-feather';

import APP_ROUTE from '../../routes/app.routes';

export const Pages = [
  {
    id: 1,
    sectionId: 1,
    icon: <Icon.HardDrive size={20} />,
    title: 'Modern',
    path: APP_ROUTE.MODERN,
  },
  {
    id: 2,
    sectionId: 1,
    icon: <Icon.PieChart size={20} />,
    title: 'Analytical',
    path: '/',
  },
  {
    id: 3,
    sectionId: 1,
    icon: <Icon.ShoppingBag size={20} />,
    title: 'eCommerce',
    path: APP_ROUTE.ECOMMERCE,
  },
  {
    id: 4,
    sectionId: 2,
    icon: <Icon.MessageSquare size={20} />,
    title: 'Chat',
    path: APP_ROUTE.CHAT,
  },
  {
    id: 5,
    sectionId: 2,
    icon: <Icon.Clipboard size={20} />,
    title: 'Notes',
    path: APP_ROUTE.NOTES,
  },
  {
    id: 6,
    sectionId: 2,
    icon: <Icon.Inbox size={20} />,
    title: 'Mail',
    path: APP_ROUTE.MAIL,
  },
  {
    id: 7,
    sectionId: 2,
    icon: <Icon.Calendar size={20} />,
    title: 'Calendar',
    path: APP_ROUTE.CALENDAR,
  },
  {
    id: 8,
    sectionId: 2,
    icon: <Icon.Users size={20} />,
    title: 'Customers',
    path: APP_ROUTE.CUSTOMERS,
  },
  {
    id: 9,
    sectionId: 3,
    icon: <Icon.ShoppingCart size={20} />,
    title: 'Shop',
    path: APP_ROUTE.SHOP,
  },
  {
    id: 10,
    sectionId: 3,
    icon: <Icon.AlertCircle size={20} />,
    title: 'Alert',
    path: APP_ROUTE.ALERT,
  },
  {
    id: 11,
    sectionId: 3,
    icon: <Icon.User size={20} />,
    title: 'User Profile',
    path: APP_ROUTE.USER_PROFILE,
  },
  {
    id: 12,
    sectionId: 3,
    icon: <Icon.Edit size={20} />,
    title: 'Quill Editor',
    path: APP_ROUTE.QUILL_EDITOR,
  },
  {
    id: 13,
    sectionId: 3,
    icon: <Icon.GitPullRequest size={20} />,
    title: 'Treeview',
    path: APP_ROUTE.TREEVIEW,
  },
  {
    id: 14,
    sectionId: 3,
    icon: <Icon.DollarSign size={20} />,
    title: 'Pricing',
    path: APP_ROUTE.PRICING,
  },
  {
    id: 15,
    sectionId: 3,
    icon: <Icon.Type size={20} />,
    title: 'Typography',
    path: APP_ROUTE.TYPOGRAPHY,
  },
  {
    id: 16,
    sectionId: 3,
    icon: <Icon.Feather size={20} />,
    title: 'Feather Icons',
    path: APP_ROUTE.FEATHER_ICONS,
  },
  {
    id: 17,
    sectionId: 3,
    icon: <Icon.Clock size={20} />,
    title: 'Timeline',
    path: APP_ROUTE.TIMELINE,
  },
  {
    id: 18,
    sectionId: 4,
    icon: <Icon.Box size={20} />,
    title: 'Form Elements',
    path: APP_ROUTE.FORM_ELEMENTS,
  },
  {
    id: 19,
    sectionId: 4,
    icon: <Icon.FileText size={20} />,
    title: 'Form Layout',
    path: APP_ROUTE.FORM_LAYOUT,
  },
  {
    id: 20,
    sectionId: 4,
    icon: <Icon.FilePlus size={20} />,
    title: 'Form Custom',
    path: APP_ROUTE.FORM_CUSTOM,
  },
  {
    id: 21,
    sectionId: 4,
    icon: <Icon.Codepen size={20} />,
    title: 'Form Wizard',
    path: APP_ROUTE.FORM_WIZARD,
  },
  {
    id: 22,
    sectionId: 5,
    icon: <Icon.Layout size={20} />,
    title: 'Tables',
    path: APP_ROUTE.TABLES,
  },
  {
    id: 23,
    sectionId: 6,
    icon: <Icon.Archive size={20} />,
    title: 'Widget Feed',
    path: APP_ROUTE.WIDGET_FEED,
  },
  {
    id: 24,
    sectionId: 6,
    icon: <Icon.Grid size={20} />,
    title: 'Widget Apps',
    path: APP_ROUTE.WIDGET_APPS,
  },
  {
    id: 25,
    sectionId: 7,
    icon: <Icon.Activity size={20} />,
    title: 'Line Chart',
    path: APP_ROUTE.LINE_CHART,
  },
  {
    id: 26,
    sectionId: 7,
    icon: <Icon.BarChart size={20} />,
    title: 'Gradient Chart',
    path: APP_ROUTE.GRADIENT_CHART,
  },
  {
    id: 27,
    sectionId: 7,
    icon: <Icon.BarChart2 size={20} />,
    title: 'Doughnut & Pie',
    path: APP_ROUTE.DOUGHNUT_PIE_CHART,
  },
  {
    id: 28,
    sectionId: 7,
    icon: <Icon.Aperture size={20} />,
    title: 'Area Chart',
    path: APP_ROUTE.AREA_CHART,
  },
  {
    id: 29,
    sectionId: 7,
    icon: <Icon.Circle size={20} />,
    title: 'Column Chart',
    path: APP_ROUTE.COLUMN_CHART,
  },
  {
    id: 30,
    sectionId: 7,
    icon: <Icon.Loader size={20} />,
    title: 'Candlestick Chart',
    path: APP_ROUTE.CANDLESTICK_CHART,
  },
  {
    id: 31,
    sectionId: 7,
    icon: <Icon.Octagon size={20} />,
    title: 'Radialbar & Radar',
    path: APP_ROUTE.RADIAL_RADAR_CHART,
  },
  {
    id: 32,
    sectionId: 8,
    icon: <Icon.LogIn size={20} />,
    title: 'Sign In',
    path: APP_ROUTE.SIGN_IN,
  },
  {
    id: 33,
    sectionId: 8,
    icon: <Icon.UserPlus size={20} />,
    title: 'Sign Up',
    path: APP_ROUTE.SIGN_UP,
  },
  {
    id: 34,
    sectionId: 8,
    icon: <Icon.RefreshCcw size={20} />,
    title: 'Reset Password',
    path: APP_ROUTE.RESET_PASSWORD,
  },
  {
    id: 35,
    sectionId: 8,
    icon: <Icon.AlertTriangle size={20} />,
    title: 'Error',
    path: APP_ROUTE.ERROR,
  },
];
